################
### MONITORS ###
################

monitor=LVDS-1,1366x768@60.10300,0x0,1
monitor=VGA-1,1920x1080@60,1366x0,1
workspace=name:1,monitor:VGA-1
exec-once = hyprctl dispatch workspace 1

workspace = 1, monitor:VGA-1
workspace = 2, monitor:VGA-1
workspace = 3, monitor:VGA-1
workspace = 4, monitor:VGA-1
workspace = 5, monitor:VGA-1
workspace = 6, monitor:LVDS-1
workspace = 7, monitor:LVDS-1
workspace = 8, monitor:LVDS-1
workspace = 9, monitor:LVDS-1
workspace = 10, monitor:LVDS-1

